name: unisearch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  easy_container: ^1.0.4+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
